%%metro title: nfdata-omics/spatialomics
%%metro legend: bl

%%metro files: fastq_in | FASTQ | Raw sequencing reads
%%metro dir: spaceranger_existing_in | Outs | Preprocessed Space Ranger output
%%metro file: microscopy_image_in | Image | High-resolution microscopy image
%%metro files: reference_files_in | Reference | Reference files

%%metro file: report_out | HTML | MultiQC report
%%metro dir: results_out | Results | Published outputs

%%metro line: fastq_route | Start from FASTQ files | #2699CB
%%metro line: processed_route | Start from processed Space Ranger outs | #96C95D


graph LR

    subgraph fastq_alignment [Space Ranger alignment and quantification]
        reference_files_in[ ]
        fastq_in[ ]
        prepare_ref[Prepare Space Ranger ref.]
        spaceranger_count[Space Ranger count]
        reference_files_in -->|fastq_route| prepare_ref
        spaceranger_count -->|fastq_route| all_spaceranger
        prepare_ref -->|fastq_route| spaceranger_count
        fastq_in -->|fastq_route| spaceranger_count
    end

    spaceranger_count -->|fastq_route| space_ranger_outputs

    subgraph visium_qc [HD Visium data conversion and quality control]
        spaceranger_existing_in[ ]
        space_ranger_outputs[Space Ranger outputs]
        collect_spaceranger_metrics[Collect Space Ranger metrics]
        spaceranger_to_zarr[Convert to SpatialData/Zarr]
        spatial_quality_control[Compute and aggregate Spatial QC]

        spaceranger_existing_in -->|processed_route| space_ranger_outputs
        space_ranger_outputs -->|fastq_route,processed_route| spaceranger_to_zarr
        spaceranger_to_zarr -->|fastq_route,processed_route| spatial_quality_control
        space_ranger_outputs -->|fastq_route,processed_route| collect_spaceranger_metrics

    end

    spatial_quality_control -->|fastq_route,processed_route| segmentation_plots

    subgraph image_segmentation [Image segmentation]
        microscopy_image_in[ ]
        image_to_tiff[Microscopy image to memmappable OME-TIFF]
        cellpose[Cellpose tiled segmentation]
        segmentation_plots[Segmentation plots and statistics]

        microscopy_image_in -->|fastq_route,processed_route| image_to_tiff
        image_to_tiff -->|fastq_route,processed_route| cellpose
        cellpose -->|fastq_route,processed_route| segmentation_plots
    end

    segmentation_plots -->|fastq_route,processed_route| bin2cell

    subgraph single_cell_analysis [Single-cell data analysis]
        bin2cell[bin2cell cell-level aggregation]
        single_cell_annotation[Single-cell annotation]

        bin2cell -->|fastq_route,processed_route| single_cell_annotation
    end

    space_ranger_outputs -->|fastq_route,processed_route| lower_resolution_visium

    subgraph deconvolution [Deconvolution analysis]
        lower_resolution_visium[Lower-resolution Visium signal]
        cell_type_deconvolution[Cell type deconvolution]

        lower_resolution_visium -->|fastq_route,processed_route| cell_type_deconvolution
    end

    cell_type_deconvolution -->|fastq_route,processed_route| multiqc
    cell_type_deconvolution -->|fastq_route,processed_route| results_out
    single_cell_annotation -->|fastq_route,processed_route| multiqc
    single_cell_annotation -->|fastq_route,processed_route| results_out

    subgraph reporting [Reporting and output]
        multiqc[MultiQC]
        report_out[ ]
        results_out[ ]

        multiqc -->|fastq_route,processed_route| report_out
    end
